SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

drop table if exists `_apps`;
DROP TABLE IF EXISTS `_groups`;
DROP TABLE IF EXISTS `_users`;
DROP TABLE IF EXISTS `_user-_group`;
DROP TABLE IF EXISTS `_errors`;
DROP TABLE IF EXISTS `_user-uids`;
DROP TABLE IF EXISTS `_user-emails`;
DROP TABLE IF EXISTS `_user-hashes`;
DROP TABLE IF EXISTS `_app-tables`;
drop table if exists `_app-db-touches`;
drop table if exists `_app-tpl-touches`;
drop table if exists `_app-controller-method-touches`;
DROP TABLE IF EXISTS `_app-tpl-rights`;
DROP TABLE IF EXISTS `_app-_group-tpl-rights`;
DROP TABLE IF EXISTS `_app-_user-tpl-rights`;
DROP TABLE IF EXISTS `_app-db-rights`;
DROP TABLE IF EXISTS `_app-_group-db-rights`;
DROP TABLE IF EXISTS `_app-_user-db-rights`;
DROP TABLE IF EXISTS `_app-controller-method-rights`;
DROP TABLE IF EXISTS `_app-_group-controller-method-rights`;
DROP TABLE IF EXISTS `_app-_user-controller-method-rights`;
DROP TABLE IF EXISTS `_settings`;
DROP TABLE IF EXISTS `_group-_setting`;
DROP TABLE IF EXISTS `_user-_setting`;
DROP TABLE IF EXISTS `_user-email-state`;
DROP TABLE IF EXISTS `_user-uid-state`;
DROP TABLE IF EXISTS `_user-hash-state`;
